Agrego validaciones para los endpoints y refactor de los mismos
hifrontendcafe/calomentor pull request #17
Opened 2021-08-17 16:36 UTC by anaggithub

Holi!! Estuve trabajando un poco en los endpoints ya creados para mejorarlos y agregarles las validaciones que decidimos el otro día.

1. Hice varios refactors:
- Cree una función throwResponse y la uso en todos los endpoints, esto porque había un montón de código repetido. En dicha función utilizo el type GlobalResponse que había creado Fran. 

 
![image](https://user-images.githubusercontent.com/47753872/129764801-0f73a5d3-0e85-4270-be64-0bcf493247b5.png)

- Actualicé todas las funciones para que tengan una estructura parecida, ahora me parece que son mucho más simples de leer y entender lo que hacen:

 
![image](https://user-images.githubusercontent.com/47753872/129764821-b5f6a4c6-71d3-4a02-af4f-da2e6c39a1dd.png)

- Cree en utils un archivo validations, en el cual agregué una función que reúne todas las validaciones de campos que tienen en común el create y el update de users.

 
![image](https://user-images.githubusercontent.com/47753872/129764831-4b8419b9-4d9a-40ea-b347-9ed152be2f43.png)

También actualicé los nombres de los campos al idioma inglés y mejoré un poco los messages de las responses.

2.  Ni create user o update user esperan la propiedad isActive en el body. Esta propiedad en la función createUser se crea y setea sola en false por defecto. Para modificar este campo se debería utilizar el endpoint de activación de usuario: dev/user/activate. Esto a partir de lo que charlamos en la última meet.

3. Actualicé la función de activación del usuario, ejemplo de cómo sería la llamada a este endpoint:
![image](https://user-images.githubusercontent.com/47753872/129765649-66f713e6-f5ba-498c-962f-fbb990114a52.png)

4. Agregué validaciones para las rutas Update User, Actívate User y Delete User, que solo lo hagan si existe el id, si no, que devuelvan 404. Ej:
![image](https://user-images.githubusercontent.com/47753872/129765505-99507a60-438e-478d-be2d-20e26e4c469c.png)

5. En Create User agregué una validación para que solo cree el usuario si el id no existe. 
![image](https://user-images.githubusercontent.com/47753872/129765557-c89ec486-4583-4532-8a22-4ad933017922.png)

2021-08-19 01:12 UTC, franmper requested changes
Muuy bueno el pr, deje un solo comentario

2021-08-19 01:12 UTC, franmper commented on services/userService.ts
> +  if (!isActive || typeof isActive !== "boolean") {
En el caso de desactivar un mentor aca va a devolver error, la que se me ocurre que podrías hacer posiblemente es chequear que no sea null o undefined.

2021-08-22 01:27 UTC, merged

2021-08-22 03:22 UTC, anaggithub commented on services/userService.ts
> +  if (!isActive || typeof isActive !== "boolean") {
Holi! No entiendo por qué devolvería error!! En qué caso pasaría eso?
Si le mando null me devuelve esto:
![image](https://user-images.githubusercontent.com/47753872/130340854-e0c21974-b2fd-4c0b-9b36-04c94777d09e.png)

Si no le mando nada: 
![image](https://user-images.githubusercontent.com/47753872/130340857-83ce9f95-f51a-4b32-a3be-00f3ec290bba.png)

2021-08-22 03:37 UTC, franmper commented on services/userService.ts
> +  if (!isActive || typeof isActive !== "boolean") {
En esos casos esta bien, el tema es si desactivas un mentor le deberias pasar un false y ahi deberia tirarte error

2021-08-22 04:00 UTC, SebasEC96 commented on services/userService.ts
> +  if (!isActive || typeof isActive !== "boolean") {
Pasa que si le pasas isActive en false para desactivar a un usuario entraría en ese error y creo que la idea es que sirva para activar/desactivar al mentor

2021-08-23 15:03 UTC, anaggithub commented on services/userService.ts
> +  if (!isActive || typeof isActive !== "boolean") {
Haaaa ahora entendí. Es verdad, si mandas false entra al bad request. Estuve probando y di con esto, estaría bien?
![image](https://user-images.githubusercontent.com/47753872/130470274-4389885c-3f47-4b71-904d-f7a0f12a0279.png)

Si no le mando nada:
![image](https://user-images.githubusercontent.com/47753872/130470321-42e14ab6-90b0-40ff-81f8-515a057ebd9b.png)


Si mando true:
![image](https://user-images.githubusercontent.com/47753872/130470403-497731d6-9aaa-4844-847f-f6115429ce58.png)


Si mando false:
![image](https://user-images.githubusercontent.com/47753872/130470463-5a0a87ac-ff3f-4bc2-a1a0-a53656625984.png)

2021-08-23 15:35 UTC, franmper commented on services/userService.ts
> +  if (!isActive || typeof isActive !== "boolean") {
Sii, perfecto eso!! Lo que si vas a tener que hacer un pr nuevo, por que con sebas el sabado estuvimos probando cosas y teniamos que hacer el merge para probar directo desde el front.